core/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from posts import views

urlpatterns = [
    path("", views.home_view, name="home"),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("posts/", include("posts.urls")),
    path("profile/", include("users.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += debug_toolbar_urls()

posts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from posts import views

app_name = "posts"

urlpatterns = [
    path("category/<slug:tag_slug>", views.home_view, name="category"),
    path("create/", views.post_create_view, name="create"),
    path(
        "comment/<str:comment_id>/delete/", views.comment_delete, name="comment_delete"
    ),
    path("reply/<str:reply_id>/delete/", views.reply_delete, name="reply_delete"),
    path("post/<uuid:pk>/like", views.like_post, name="like_post"),
    path("comment/<pk>/like", views.like_comment, name="like_comment"),
    path("reply/<pk>/like", views.like_reply, name="like_reply"),
    path("comment/<str:post_id>/", views.comment_sent, name="comment_sent"),
    path("reply/<str:comment_id>/", views.reply_sent, name="reply_sent"),
    path("<uuid:post_id>/delete/", views.post_delete_view, name="delete"),
    path("<uuid:post_id>/edit/", views.post_edit_view, name="edit"),
    path("<pk>/", views.post_page_view, name="detail"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path("", views.detail_view, name="profile"),
    path("edit/", views.edit_view, name="edit"),
    path("delete/", views.delete_view, name="delete"),
    path("onboarding/", views.edit_view, name="onboarding"),
    path("<str:username>/", views.detail_view, name="profile"),
]

posts/models.py
from uuid import uuid4

from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Post(models.Model):
    id = models.UUIDField(default=uuid4, primary_key=True, unique=True, editable=True)
    artist = models.CharField(max_length=500, null=True)
    title = models.CharField(max_length=500)
    image = models.URLField(max_length=512)
    url = models.URLField(max_length=512, null=True)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    tags = models.ManyToManyField("Tag", blank=True)
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, related_name="posts"
    )
    likes = models.ManyToManyField(User, related_name="like_posts", through="LikePost")

    def __str__(self) -> str:
        return str(self.title)

    class Meta:
        ordering = ["-created"]


class LikePost(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.user.username} liked {self.post.title}"


class Tag(models.Model):
    name = models.CharField(max_length=20)
    slug = models.SlugField(max_length=20, unique=True)
    image = models.FileField(upload_to="icons/", null=True, blank=True)
    order = models.IntegerField(null=True)

    def __str__(self) -> str:
        return self.name

    class Meta:
        ordering = ["order"]


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    likes = models.ManyToManyField(
        User, related_name="like_comments", through="LikeComment"
    )

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"Comment by {self.author.username if self.author.username else 'no author'} on {self.post.title}"


class LikeComment(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} liked {self.comment.content}"


class Reply(models.Model):
    comment = models.ForeignKey(
        Comment, on_delete=models.CASCADE, related_name="replies"
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="replies")
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    likes = models.ManyToManyField(
        User, related_name="like_replies", through="LikeReply"
    )

    def __str__(self):
        return f"Reply by {self.author.username if self.author.username else 'no author'} on {self.comment.post.title}"


class LikeReply(models.Model):
    reply = models.ForeignKey(Reply, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

posts/forms.py
from django import forms
from django.forms import ModelForm

from posts.models import Comment, Post, Reply


class PostCreateForm(ModelForm):
    class Meta:
        model = Post
        fields = ["url", "body", "tags"]
        labels = {"body": "Caption", "tags": "Category"}

        widgets = {
            "body": forms.Textarea(
                attrs={
                    "rows": 3,
                    "placeholder": "Add a caption ...",
                    "class": "font1 text-4xl",
                }
            ),
            "url": forms.TextInput(attrs={"placeholder": "Add url"}),
            "tags": forms.CheckboxSelectMultiple(),
        }


class PostEditForm(ModelForm):
    class Meta:
        model = Post
        fields = ["body", "tags"]
        labels = {"body": "Caption", "tags": "Category"}

        widgets = {
            "body": forms.Textarea(
                attrs={
                    "rows": 3,
                    "placeholder": "Add a caption ...",
                    "class": "font1 text-4xl",
                }
            ),
            "url": forms.TextInput(attrs={"placeholder": "Add url"}),
            "tags": forms.CheckboxSelectMultiple(),
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]
        widgets = {
            "content": forms.Textarea(
                attrs={"rows": 3, "placeholder": "Add a comment ..."}
            ),
        }


class ReplyForm(ModelForm):
    class Meta:
        model = Reply
        fields = ["content"]
        widgets = {
            "content": forms.Textarea(
                attrs={"rows": 3, "placeholder": "Add a reply ..."}
            ),
        }

posts/views.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render

from posts.forms import CommentForm, PostCreateForm, PostEditForm, ReplyForm
from posts.utils import scrape_flickr

from .models import Comment, Post, Reply, Tag


def home_view(request, tag_slug=None):
    tag = ""
    if tag_slug:
        posts = Post.objects.filter(tags__slug=tag_slug)
        tag = get_object_or_404(Tag, slug=tag_slug)
    else:
        posts = Post.objects.all()

    paginator = Paginator(posts, 2)
    page_number = int(request.GET.get("page", 1))
    posts = paginator.get_page(page_number)

    context = {"posts": posts, "tag": tag, "page": page_number}

    if request.htmx:
        return render(request, "snippets/loop_home_posts.html", context)

    return render(request, "posts/home.html", context)


def post_create_view(request):
    if request.method != "POST":
        return render(request, "posts/post_create.html", {"form": PostCreateForm()})

    form = PostCreateForm(request.POST)
    if not form.is_valid():
        messages.error(request, "Form is not valid. Please check your input.")
        return render(request, "posts/post_create.html", {"form": form})

    post = form.save(commit=False)
    url = form.cleaned_data["url"]
    result = scrape_flickr(url)

    if result:
        post.image = result.get("image", "")
        post.title = result.get("title", "")
        post.artist = result.get("artist", "")

    post.author = request.user
    post.save()
    form.save_m2m()

    if result and all([post.image, post.title, post.artist]):
        messages.success(request, "Post created successfully with all data!")
    elif result:
        messages.warning(request, "Post created, but some data couldn't be scraped.")
    else:
        messages.error(
            request, "Failed to scrape data. Post created with form data only."
        )

    return redirect("home")


def post_delete_view(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.method == "POST":
        post.delete()
        messages.success(request, "Post deleted successfully!")

        return redirect("home")

    return render(request, "posts/post_delete.html", {"post": post})


def post_edit_view(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = PostEditForm(instance=post)
    context = {"post": post, "form": form}

    if request.method == "POST":
        form = PostEditForm(instance=post, data=request.POST)

        if form.is_valid():
            form.save(commit=False)
            form.save_m2m()
            messages.success(request, "Post edited successfully")
            return redirect("home")

    return render(request, "posts/post_edit.html", context)


def post_page_view(request, pk):
    post = get_object_or_404(Post, id=pk)
    commentform = CommentForm()
    replyform = ReplyForm()

    if request.htmx:
        if "top" in request.GET:
            comments = (
                post.comments.annotate(num_likes=Count("likes"))
                .filter(num_likes__gt=0)
                .order_by("-num_likes")
            )
        else:
            comments = post.comments.all()
        return render(
            request,
            "snippets/loop_postpage_comments.html",
            {"comments": comments, "replyform": replyform},
        )

    context = {
        "post": post,
        "commentform": commentform,
        "replyform": replyform,
    }

    return render(request, "posts/post_page.html", context)


def comment_sent(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    commentform = CommentForm(request.POST)
    replyform = ReplyForm()

    if request.method == "POST":
        if commentform.is_valid():
            comment = commentform.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()

    context = {"post": post, "comment": comment, "replyform": replyform}

    return render(request, "snippets/add_comment.html", context)


def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id, author=request.user)

    if request.method == "POST":
        comment.delete()
        return redirect("posts:detail", comment.post.id)

    return render(request, "posts/comment_delete.html", {"comment": comment})


def reply_sent(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id, author=request.user)
    replyform = ReplyForm(request.POST)

    if request.method == "POST":
        if replyform.is_valid():
            reply = replyform.save(commit=False)
            reply.comment = comment
            reply.author = request.user
            reply.save()

    context = {"reply": reply, "comment": comment, "replyform": replyform}

    return render(request, "snippets/add_reply.html", context)


def reply_delete(request, reply_id):
    reply = get_object_or_404(Reply, pk=reply_id, author=request.user)

    if request.method == "POST":
        reply.delete()
        return redirect("posts:detail", reply.comment.post.id)

    return render(request, "posts/reply_delete.html", {"reply": reply})


def like_toggle(model):
    def inner_func(func):
        def wrapper(request, *args, **kwargs):
            post = get_object_or_404(model, id=kwargs.get("pk"))
            user_exist = post.likes.filter(username=request.user.username).exists()

            if post.author != request.user:
                if user_exist:
                    post.likes.remove(request.user)
                else:
                    post.likes.add(request.user)

            return func(request, post)

        return wrapper

    return inner_func


@like_toggle(Post)
def like_post(request, post):
    return render(request, "snippets/likes.html", {"post": post})


@like_toggle(Comment)
def like_comment(request, post):
    return render(request, "snippets/likes_comment.html", {"comment": post})


@like_toggle(Reply)
def like_reply(request, post):
    return render(request, "snippets/likes_reply.html", {"reply": post})

templates/posts/comment.html
{% load static %}
<comment class="card p-4 !mb-4">
    <div class="flex justify-between items-center"> 
        {% if comment.author %}
        <a class="flex items-center gap-1 mb-2" href="{% url 'users:profile' comment.author.username  %}">
            <img class="w-8 h-8 object-cover rounded-full" src="{{ comment.author.profile.avatar }}"> 
            <span class="font-bold hover:underline">{{ comment.author.profile.name }}</span>
            <span class="text-sm font-normal text-gray-400">@{{ comment.author.username }}</span>
        </a>
        {% else %}
        <div class="flex items-center gap-1 mb-4">
            <img class="w-8 h-8 object-cover rounded-full" src="{% static 'images/avatar_default.svg' %}">
            <span class="text-gray-500">no author</span>
        </div>
        {% endif %}
    </div>
    <p class="text-xl px-2">
        {{ comment.content }}
    </p>
     <div x-data="{ repliesOpen: false }" class="flex items-center justify-between flex-wrap text-sm px-2"> <a @click="repliesOpen = !repliesOpen" class="font-bold hover:underline cursor-pointer">
            {% if comment.replies.count or user.is_authenticated %}
            <div class="inline-block" x-bind:class="repliesOpen && 'rotate-90 duration-300'">
                <svg transform ="rotate(90)" width="9" height="9" viewBox="0 0 25 25">
                    <path d="M24 22h-24l12-20z"/>
                </svg>
            </div>
            {% endif %}
            {% if comment.replies.count %}
            Replies
            <span id="repliescount-{{ comment.id }}" class="font-light text-gray-500 ml-1">{{ comment.replies.count }}</span>
            {% else %}
                {% if user.is_authenticated %}
                Add Reply
                {% endif %}
            {% endif %}
        </a>
        <div class="flex items-center gap-4 [&>a:hover]:underline">
            {% include 'snippets/likes_comment.html' %}
            {% if user.is_authenticated and comment.author == user %}
            <a href="{% url 'posts:comment_delete' comment.id %}">Delete</a>
            {% endif %}
        </div>

        <div x-show="repliesOpen" x-cloak class="basis-full mt-3 pl-8 grid grid-cols-1">
            {% for reply in comment.replies.all %}
            {% include 'posts/reply.html' %}
            {% endfor %}

            {% if user.is_authenticated %}
            <form class="replyform flex justify-between" autocomplete="off"
            hx-post="{% url 'posts:reply_sent' comment.id %}"
            hx-target="this" 
            hx-swap="outerHTML" >
                {% csrf_token %}
                {{ replyform }}
                <button class="block" type="submit">Submit</button>
            </form>
            {% endif %} 
        </div>
    </div>  
</comment>

templates/posts/comment_delete.html
{% extends 'layouts/b.html' %}

{% block content %}

<h1>Delete Comment</h1>

{% include 'posts/comment.html' %}

<p class="my-6">Are you sure you want to delete this comment?</p>

<form method='POST'>
    {% csrf_token %}
    <button type="submit">Confirm</button>
    <a class="button secondaryAction ml-1" href="{{ request.META.HTTP_REFERER }}">Go Back</a>
</form>

{% endblock %}

templates/posts/home.html
{% extends 'layouts/a.html' %}

{% block content %}
  {% for post in posts %}
    {% include 'posts/post.html' %}
  {% endfor %}

  {% comment %} <div hx-get="{% if tag %}
      {% url 'category' tag.slug %}
    {% else %}
      {% url 'home' %}
    {% endif %}?page={{ page|add:1 }}"
    hx-trigger="revealed"
    hx-target="this"
    hx-swap="outerHTML"></div> {% endcomment %}
{% endblock %}

templates/posts/post.html
{% load static %}

<article class="card">
  <div class="flex items-center justify-between px-4 h-14">
      <h3 class="text-start leading-5 mr-1">{{ post.title }}</h3>
       <div class="text-sm text-gray-400 truncate">flickr
        <a href="{{ post.url }}" class="hover:underline ml-1" target="blank">@{{ post.artist }}</a>
      </div> 
  </div>
  <figure>
      <a href="{}"><img class="w-full" src="{{ post.image }}"></a>
  </figure>
  <div class="p-4 pb-2">
      {% if post.author %}
      <a class="flex items-center gap-1 mb-4" href="{% url 'users:profile' post.author.username %}">
          <img class="w-8 h-8 object-cover rounded-full" src="{{ post.author.profile.avatar }}">  
          <span class="font-bold hover:underline">{{ post.author.profile.name }}</span>
          <span class="text-sm text-gray-400">@{{ post.author.username }}</span>          
      </a>
      {% else %}
      <div class="flex items-center gap-1 mb-4">
          <img class="w-8 h-8 object-cover rounded-full" src="{% static 'images/avatar_default.svg' %}">
          <span class="text-gray-500">no author</span>
      </div>
      {% endif %} 
      <p class="text-5xl mb-10 px-4 font1">{{ post.body }}</p>
       <div class="flex items-center gap-2 text-sm mb-5 flex-wrap">
          {% for tag in post.tags.all %}
          <a href="{% url 'posts:category' tag.slug %}" class="bg-gray-200 rounded-full px-3 py-1 hover:bg-gray-800 hover:text-white">{{ tag }}</a>
          {% endfor %}
      </div> 
      <div class="flex items-center justify-between text-sm px-2">
           <a class="font-bold hover:underline" href="{% url 'posts:detail' post.id %}">
              {% if post.comments.count %}
              Comments
              <span id="commentscount-{{ post.id }}" class="font-light text-gray-500 ml-1">{{ post.comments.count }}</span>
              {% else %}
                  {% if user.is_authenticated %}
                  Add comment
                  {% endif %}
              {% endif %}
          </a> 
           <div class="flex items-center gap-4 [&>a:hover]:underline">
              {% include 'snippets/likes.html' %}
               {% if user.is_authenticated and user == post.author %} 
                <a href="{% url 'posts:edit' post.id%}">Edit</a>
              <a href="{% url 'posts:delete' post.id %}">Delete</a>
               {% endif %} 
          </div>
      </div>
  </div>
</article>

templates/posts/post_create.html
{% extends 'layouts/b.html' %}

{% block content %}

<h1>Create Post</h1>
<div class="card !p-8">
    
    <div class="flex items-center mb-6">
        <img class="h-5 object-cover mr-1" src="https://img.icons8.com/small/96/333333/search--v1.png"/>
        <a href="https://www.flickr.com/explore" target="_blank" class="hover:underline text-gray-500">Find an image on Flickr</a>
    </div>

    <form method='POST'>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="mt-1">Submit Post</button>
        <a class="button secondaryAction ml-1" href="{{ request.META.HTTP_REFERER }}">Cancel</a>
    </form>
</div>

{% endblock %}

templates/posts/post_delete.html
{% extends 'layouts/b.html' %}

{% block content %}

<div class="md:flex items-center">
    <div class="w-full md:max-w-sm mr-6 md:[&>*>*>p]:text-4xl">
        
        {% include 'posts/post.html' %}

    </div>
    <div>
        <h1>Delete Post</h1>
        <p class="mb-6">Are you sure you want to delete this post?</p>
        
        <form method='POST'>
            {% csrf_token %}
            <button type="submit">Confirm</button>
            <a class="button secondaryAction ml-1" href="{{ request.META.HTTP_REFERER }}">Go Back</a>
        </form>
    </div>
</div>

{% endblock %}

templates/posts/post_edit.html
{% extends 'layouts/b.html' %}

{% block content %}

<h1>Edit Post</h1>
<div class="card p-4">
    <div class="flex items-center mb-4">
        <img class="w-20 h-20 object-cover rounded-xl mr-4" src="{{ post.image }}">
        <h3 class="text-lg font-bold">{{ post.title }}</h3>
    </div>
    
    <div class="pb-2">
        <form method='POST'>
            {% csrf_token %}
            {{ form.as_p }}
            <div class="pt-4">
                <button type="submit">Submit</button>
                <a class="button secondaryAction ml-1" href="{{ request.META.HTTP_REFERER }}">Go Back</a>
            </div>
        </form>
    </div>
</div>

{% endblock %}

templates/posts/post_page.html
{% extends 'layouts/a.html' %}

{% block content %}

{% include 'posts/post.html' %}

{% if user.is_authenticated %}
<div class="card !pb-0 -mt-3">
    <form class="flex items-center p-4" autocomplete="off"
    hx-post="{% url 'posts:comment_sent' post.id %}" 
    hx-target="#tab-contents" 
    hx-swap="afterbegin"
    _="on htmx:afterRequest reset() me" >
        {% csrf_token %}
        {{ commentform }}
        <button @click="open = false" class="block ml-2" type="submit">Submit</button>
    </form>
</div>
{% endif %} 

<div class="mb-20">
    <div id="tabs" class="ml-4 flex gap-1 mb-4 {% if not post.comments.count %}hidden{% endif %}" hx-target="#tab-contents" hx-swap="innerHTML"
    _="on htmx:afterOnLoad take .selected for event.target">
        <a hx-get="{% url 'posts:detail' post.id %}">Newest First</a> 
        <a hx-get="{% url 'posts:detail' post.id %}?top">Top Comments</a>
    </div>

    <div id="tab-contents">
        {% for comment in post.comments.all %}
        {% include 'posts/comment.html' %}
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/posts/posts.html
{% load static %}

{% for post in posts %}

{% include 'posts/post.html' %}

{% endfor %}

templates/posts/reply.html
{% load static %}
<reply class="flex items-end justify-between py-4 border-t">
  <div class="flex">
    {% if reply.author %}
      <a href="{% url 'users:profile' reply.author.username %}"><img class="w-8 h-8 object-cover rounded-full mr-2" src="{{ reply.author.profile.avatar }}" /></a>
    {% else %}
      <img class="w-8 h-8 object-cover rounded-full" src="{% static 'images/avatar_default.svg' %}" />
    {% endif %}
    <div class="w-fit">
      {% if reply.author %}
        <a class="block" href="">
          <span class="font-bold hover:underline">{{ reply.author.profile.name }}</span>
          <span class="text-sm text-gray-400">@{{ reply.author.username }}</span>
        </a>
      {% else %}
        <span class="text-gray-500">no author</span>
      {% endif %}
      <div class="mr-3">{{ reply.content }}</div>
    </div>
  </div>
  <div class="flex items-center gap-4 [&>a:hover]:underline">
    {% include 'snippets/likes_reply.html' %}
    {% if user.is_authenticated and reply.author == user %}
      <a href="{% url 'posts:reply_delete' reply.id %}">Delete</a>
    {% endif %}
  </div>
</reply>

templates/posts/reply_delete.html
{% extends 'layouts/b.html' %}

{% block content %}

<h1>Delete Reply</h1>

<div class=" card px-6 pt-3 text-md mb-6 [&>*>*>a]:text-sm">

    {% include 'posts/reply.html' %}

</div>

<p class="mb-6">Are you sure you want to delete this reply?</p>

<form method='POST'>
    {% csrf_token %}
    <button type="submit">Confirm</button>
    <a class="button secondaryAction ml-1" href="{{ request.META.HTTP_REFERER }}">Go Back</a>
</form>


{% endblock %}