core/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from posts import views

urlpatterns = [
    path("", views.home_view, name="home"),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("posts/", include("posts.urls")),
    path("profile/", include("users.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += debug_toolbar_urls()

posts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from posts import views

app_name = "posts"

urlpatterns = [
    path("category/<slug:tag_slug>", views.home_view, name="category"),
    path("create/", views.post_create_view, name="create"),
    path(
        "comment/<str:comment_id>/delete/", views.comment_delete, name="comment_delete"
    ),
    path("reply/<str:reply_id>/delete/", views.reply_delete, name="reply_delete"),
    path("post/<uuid:pk>/like", views.like_post, name="like_post"),
    path("comment/<pk>/like", views.like_comment, name="like_comment"),
    path("reply/<pk>/like", views.like_reply, name="like_reply"),
    path("comment/<str:post_id>/", views.comment_sent, name="comment_sent"),
    path("reply/<str:comment_id>/", views.reply_sent, name="reply_sent"),
    path("<uuid:post_id>/delete/", views.post_delete_view, name="delete"),
    path("<uuid:post_id>/edit/", views.post_edit_view, name="edit"),
    path("<pk>/", views.post_page_view, name="detail"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path("", views.detail_view, name="profile"),
    path("edit/", views.edit_view, name="edit"),
    path("delete/", views.delete_view, name="delete"),
    path("onboarding/", views.edit_view, name="onboarding"),
    path("<str:username>/", views.detail_view, name="profile"),
]

templates/includes/header.html
{% load static %}
<header class="flex items-center justify-between bg-gray-800 h-20 px-8 text-white sticky top-0 z-40">
    <div>
        <a class="flex items-center gap-2" href="/">
            <img class="h-6" src="{% static 'images/logo.svg' %}" alt="Logo"/>
            <span class="text-lg font-bold">Project Title</span>
        </a>
    </div>
    <nav class="block relative">
        <ul class="navitems flex items-center justify-center h-full">
             {% if request.user.is_authenticated %}
             <li><a href="{% url 'home' %}">Home</a></li>
             <li><a href="{% url 'posts:create' %}">Create Post</a></li>
            <li x-data="{ dropdownOpen: false }" class="relative">
                <a @click="dropdownOpen = !dropdownOpen" @click.away="dropdownOpen = false" class="cursor-pointer select-none">
                    <img class="h-8 w-8 rounded-full object-cover" src="{{ request.user.profile.avatar }}" alt="Avatar" />
                    {{ request.user.profile.name }}
                    <img x-bind:class="dropdownOpen && 'rotate-180 duration-300'" class="w-4" src="https://img.icons8.com/small/32/ffffff/expand-arrow.png" alt="Dropdown" />
                </a> 
                <div x-show="dropdownOpen" x-cloak class="absolute right-0 bg-white text-black shadow rounded-lg w-40 p-2 z-20"
                x-transition:enter="duration-300 ease-out"
                x-transition:enter-start="opacity-0 -translate-y-5 scale-90"
                x-transition:enter-end="opacity-100 translate-y-0 scale-100"
                >
                    <ul class="hoverlist [&>li>a]:justify-end">
                        <li><a href="{% url 'users:profile' %}">My Profile</a></li>
                        <li><a href="{% url 'users:edit' %}">Edit Profile</a></li>
                        <li><a href="#">Settings</a></li>
                        <li><a href="{% url 'account_logout' %}">Log Out</a></li>
                    </ul>
                </div>
             </li>
            {% else %}
            <li><a href="{% url 'account_login' %}">Login</a></li>
            <li><a href="{% url 'account_signup' %}">Signup</a></li>
            {% endif %} 
        </ul>
    </nav>
</header>

templates/includes/hero.html
{% load static %}
<header class="flex items-center justify-between bg-gray-800 h-20 px-8 text-white sticky top-0 z-40">
    <div>
        <a class="flex items-center gap-2" href="/">
            <img class="h-6" src="{% static 'images/logo.svg' %}" alt="Logo"/>
            <span class="text-lg font-bold">Project Title</span>
        </a>
    </div>
    <nav class="block relative">
        <ul class="navitems flex items-center justify-center h-full">
            {% if request.user.is_authenticated %}
            <li><a href="{% url 'home' %}">Home</a></li>
            <li x-data="{ dropdownOpen: false }" class="relative">
                <a @click="dropdownOpen = !dropdownOpen" @click.away="dropdownOpen = false" class="cursor-pointer select-none">
                    <img class="h-8 w-8 rounded-full object-cover" src="{{ request.user.profile.avatar }}" alt="Avatar" />
                    {{ request.user.profile.name }}
                    <img x-bind:class="dropdownOpen && 'rotate-180 duration-300'" class="w-4" src="https://img.icons8.com/small/32/ffffff/expand-arrow.png" alt="Dropdown" />
                </a>
                <div x-show="dropdownOpen" x-cloak class="absolute right-0 bg-white text-black shadow rounded-lg w-40 p-2 z-20"
                x-transition:enter="duration-300 ease-out"
                x-transition:enter-start="opacity-0 -translate-y-5 scale-90"
                x-transition:enter-end="opacity-100 translate-y-0 scale-100"
                >
                    <ul class="hoverlist [&>li>a]:justify-end">
                        <li><a href="#">My Profile</a></li>
                        <li><a href="#">Edit Profile</a></li>
                        <li><a href="#">Settings</a></li>
                        <li><a href="#">Log Out</a></li>
                    </ul>
                </div>
            </li>
            
            {% else %}
            <li><a href="#">Login</a></li>
            <li><a href="#">Signup</a></li>
            {% endif %}
        </ul>
    </nav>
</header>

templates/includes/messages.html
<messages>
  {% if messages %}
  <div x-data="{ showMessage: false }" >
  {% for message in messages %}
  <div class="absolute left-0 right-0 max-w-xl mx-auto mt-3 px-4 z-50 ">
      <div x-cloak class="alert-{{ message.tags }} flex items-center py-3 pl-6 pr-4 bg-blue-500 text-white rounded-lg" role="alert"
      x-show="showMessage" 
      x-init="setTimeout(() => showMessage = true, 200), setTimeout(() => showMessage = false, 6000)"
      x-transition:enter="duration-700 ease-out"
      x-transition:enter-start="opacity-0 -translate-y-5"
      x-transition:enter-end="opacity-100 translate-y-0"
      x-transition:leave="duration-200 ease-in"
      x-transition:leave-start="opacity-100 translate-y-0"
      x-transition:leave-end="opacity-0 -translate-y-5">
          <div>
              <div class="text-lg">{{ message }}</div>
          </div>
          <div class="ml-auto cursor-pointer" @click="showMessage = false">
              <svg fill="white" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" viewBox="0 0 24 24" stroke="currentColor" class="w-8 h-8 ml-2">
                  <path d="M6 18L18 6M6 6l12 12"></path>
              </svg>
          </div>
      </div> 
  </div>
  {% endfor %}
  </div>
  {% endif %}
</messages>

templates/includes/sidebar.html
{% load static %}
<aside x-show="mobileSidebarOpen" x-cloak class="md:!block col-span-full md:col-span-1 lg:mr-[20%] order-1 md:order-2" x-transition:enter="duration-300 ease-out" x-transition:enter-start="opacity-0 -mt-96" x-transition:enter-end="opacity-100 mt-0">
  <section class="card p-4">
    <h2>Categories</h2>
    <ul class="hoverlist">
      {% for category in categories %}
        <li class="{% if category.slug == tag.slug %}highlight{% endif %}">
          <a href="{% url 'posts:category' category.slug %}">
            <img class="w-8 h-8 object-cover mr-2" src="{{ category.image.url }}" />
            <span class="font-bold text-sm">{{ category.name }}</span>
          </a>
        </li>
      {% endfor %}
    </ul>
  </section>
  <section class="card p-4">
    <div class="flex items-center">
      <img class="w-7 mr-2 -mt-3" src="{% static 'images/fireheart_black.svg' %}" />
      <h2>Top Posts</h2>
    </div>
    <ul class="hoverlist">
      {% for post in top_posts %}
        <li>
          <a href="{% url 'posts:detail' post.id %}" class="flex items-stretch justify-between">
            <div class="flex items-center truncate">
              <img class="w-10 h-10 rounded-lg object-cover mr-3 shrink-0" src="{{ post.image }}" />
              {% if post.author %}
                <img class="w-6 h-6 rounded-full object-cover mr-1" src="{{ post.author.profile.avatar }}" />
                <span class="font-bold text-sm mr-1">{{ post.author.username }}</span>
              {% else %}
                <img class="w-6 h-6 rounded-full object-cover mr-1" src="{% static 'images/avatar_default.svg' %}" />
                <span class="text-sm mr-1">no author</span>
              {% endif %}
            </div>
            <span class="{% if user in post.likes.all %}
                 font-bold
              {% else %}
                 font-light
              {% endif %} text-sm  text-grey-500 shrink-0">
              {{ post.likes.count }} Like{{ post.likes.count|pluralize:'s' }} / {{ post.comments.count }}
            </span>
          </a>
        </li>
      {% endfor %}
    </ul>
  </section>
  <section class="card p-4">
    <div class="flex items-center">
      <img class="w-7 mr-2 -mt-3" src="{% static 'images/fireheart_black.svg' %}" />
      <h2>Top Comments</h2>
    </div>
    <ul class="hoverlist">
      {% for comment in top_comments %}
        <li>
          <a href="{% url 'posts:detail' comment.post.id %}" class="flex items-stretch justify-between">
            <div class="flex items-center truncate">
              {% if comment.author %}
                <img class="w-6 h-6 rounded-full object-cover mr-1" src="{{ comment.author.profile.avatar }}" />
              {% else %}
                <img class="w-6 h-6 rounded-full object-cover mr-1" src="{% static 'images/avatar_default.svg' %}" />
              {% endif %}
              <span class="font-bold text-sm mr-1 truncate">
                {% if comment.author %}
                  {{ comment.author.username }}
                {% else %}
                  <span class="font-light">no author</span>
                {% endif %}: {{ comment.body|truncatechars:10 }}
              </span>
            </div>
            <span class="{% if user in comment.likes.all %}
                
                
                
                
                
                
                font-bold






              {% else %}
                
                
                
                
                
                
                font-light






              {% endif %} text-sm text-grey-500 shrink-0">
              {{ comment.likes.count }} Like{{ comment.likes.count|pluralize:'s' }} / {{ comment.replies.count }}
            </span>
          </a>
        </li>
      {% endfor %}
    </ul>
  </section>
</aside>