core/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from posts import views

urlpatterns = [
    path("", views.home_view, name="home"),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("posts/", include("posts.urls")),
    path("profile/", include("users.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += debug_toolbar_urls()

posts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from posts import views

app_name = "posts"

urlpatterns = [
    path("category/<slug:tag_slug>", views.home_view, name="category"),
    path("create/", views.post_create_view, name="create"),
    path(
        "comment/<str:comment_id>/delete/", views.comment_delete, name="comment_delete"
    ),
    path("reply/<str:reply_id>/delete/", views.reply_delete, name="reply_delete"),
    path("post/<uuid:pk>/like", views.like_post, name="like_post"),
    path("comment/<pk>/like", views.like_comment, name="like_comment"),
    path("reply/<pk>/like", views.like_reply, name="like_reply"),
    path("comment/<str:post_id>/", views.comment_sent, name="comment_sent"),
    path("reply/<str:comment_id>/", views.reply_sent, name="reply_sent"),
    path("<uuid:post_id>/delete/", views.post_delete_view, name="delete"),
    path("<uuid:post_id>/edit/", views.post_edit_view, name="edit"),
    path("<pk>/", views.post_page_view, name="detail"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/snippets/add_comment.html
<fade-in class="opacity-0 block -mt-20 ease-in-out" _="on load transition my margin-top to 0 over 0.2 seconds then transition my opacity to 1 over 0.4 seconds">
  {% include 'posts/comment.html' %}
</fade-in>

<span hx-swap-oob="true" id="commentscount-{{ post.id }}" class="font-light text-gray-500 ml-1">{{ post.comments.count }}</span>

templates/snippets/add_reply.html
<fade-in class="opacity-0 block -mt-20 ease-in-out" _="on load transition my margin-top to 0 over 0.2 seconds then transition my opacity to 1 over 0.4 seconds">
  {% include 'posts/reply.html' %}
</fade-in>

<form class="replyform flex justify-between" autocomplete="off" hx-post="{% url 'posts:reply_sent' comment.id %}" hx-target="this" hx-swap="outerHTML">
  {% csrf_token %}
  {{ replyform }}
  <button class="block" type="submit">Submit</button>
</form>

<span hx-swap-oob="true" id="repliescount-{{ comment.id }}" class="font-light text-gray-500 ml-1">{{ comment.replies.count }}</span>

templates/snippets/likes.html
{% load static %}
<div class="flex items-center gap-4 [&>a:hover]:underline">
  {% if post.likes.count %}
    <div class="flex items-center gap-1">
      {% if user in post.likes.all %}
        <img class="w-4 -mt-1" src="{% static 'images/fireheart_red.svg' %}" />
      {% else %}
        <img class="w-4 -mt-1" src="{% static 'images/fireheart.svg' %}" />
      {% endif %}
      {{ post.likes.count }}
    </div>
  {% endif %}
  {% if user.is_authenticated and user != post.author %}
    <a class="cursor-pointer" hx-get="{% url 'posts:like_post' post.id %}" hx-target="closest div" hx-swap="outerHTML" hx-trigger="click">
      {% if user in post.likes.all %}
        <b>Liked</b>
      {% else %}
        Like
      {% endif %}
    </a>
  {% endif %}
</div>

templates/snippets/likes_comment.html
{% load static %}
<div class="flex items-center gap-4 [&>a:hover]:underline">
  {% if comment.likes.count %}
    <div class="flex items-center gap-1">
      {% if user in comment.likes.all %}
        <img class="w-4 -mt-1" src="{% static 'images/fireheart_red.svg' %}" />
      {% else %}
        <img class="w-4 -mt-1" src="{% static 'images/fireheart.svg' %}" />
      {% endif %}
      {{ comment.likes.count }}
    </div>
  {% endif %}
  {% if user.is_authenticated and user != comment.author %}
    <a class="cursor-pointer" hx-get="{% url 'posts:like_comment' comment.id %}" hx-target="closest div" hx-swap="outerHTML">
      {% if user in comment.likes.all %}
        <b>Liked</b>
      {% else %}
        Like
      {% endif %}
    </a>
  {% endif %}
</div>

templates/snippets/likes_reply.html
{% load static %}
<div class="flex items-center gap-4 [&>a:hover]:underline">
  {% if reply.likes.count %}
    <div class="flex items-center gap-1">
      {% if user in reply.likes.all %}
        <img class="w-4 -mt-1" src="{% static 'images/fireheart_red.svg' %}" />
      {% else %}
        <img class="w-4 -mt-1" src="{% static 'images/fireheart.svg' %}" />
      {% endif %}
      {{ reply.likes.count }}
    </div>
  {% endif %}
  {% if user.is_authenticated and user != reply.author %}
    <a class="cursor-pointer" hx-get="{% url 'posts:like_reply' reply.id %}" hx-target="closest div" hx-swap="outerHTML">
      {% if user in reply.likes.all %}
        <b>Liked</b>
      {% else %}
        Like
      {% endif %}
    </a>
  {% endif %}
</div>

templates/snippets/loop_home_posts.html
<fade-in class="opacity-0" _="on load transition my opacity to 1 over 0.3 seconds">
  {% for post in posts %}
    {% include 'posts/post.html' %}
  {% endfor %}

  <div hx-get="{% if tag %}{% url 'posts:category' tag.slug %}{% else %}{% url 'home' %}{% endif %}?page={{ page|add:1 }}"
  hx-trigger="revealed"
  hx-target="this"
  hx-swap="outerHTML"></div>
</fade-in>

templates/snippets/loop_postpage_comments.html
<fade-in class="opacity-0" _="on load transition my opacity to 1 over 0.2 seconds">
  {% for comment in comments %}
    {% include 'posts/comment.html' %}
  {% endfor %}
</fade-in>