core/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from posts import views

urlpatterns = [
    path("", views.home_view, name="home"),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("posts/", include("posts.urls")),
    path("profile/", include("users.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += debug_toolbar_urls()

posts/models.py
from uuid import uuid4

from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Post(models.Model):
    id = models.UUIDField(default=uuid4, primary_key=True, unique=True, editable=True)
    artist = models.CharField(max_length=500, null=True)
    title = models.CharField(max_length=500)
    image = models.URLField(max_length=512)
    url = models.URLField(max_length=512, null=True)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    tags = models.ManyToManyField("Tag", blank=True)
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, related_name="posts"
    )
    likes = models.ManyToManyField(User, related_name="like_posts", through="LikePost")

    def __str__(self) -> str:
        return str(self.title)

    class Meta:
        ordering = ["-created"]


class LikePost(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.user.username} liked {self.post.title}"


class Tag(models.Model):
    name = models.CharField(max_length=20)
    slug = models.SlugField(max_length=20, unique=True)
    image = models.FileField(upload_to="icons/", null=True, blank=True)
    order = models.IntegerField(null=True)

    def __str__(self) -> str:
        return self.name

    class Meta:
        ordering = ["order"]


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    likes = models.ManyToManyField(
        User, related_name="like_comments", through="LikeComment"
    )

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"Comment by {self.author.username if self.author.username else 'no author'} on {self.post.title}"


class LikeComment(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} liked {self.comment.content}"


class Reply(models.Model):
    comment = models.ForeignKey(
        Comment, on_delete=models.CASCADE, related_name="replies"
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="replies")
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    likes = models.ManyToManyField(
        User, related_name="like_replies", through="LikeReply"
    )

    def __str__(self):
        return f"Reply by {self.author.username if self.author.username else 'no author'} on {self.comment.post.title}"


class LikeReply(models.Model):
    reply = models.ForeignKey(Reply, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

templates/base.html
{% load static %}
{% load django_htmx %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Django Template">
    <title>Project Title</title>
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
    <script src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js" defer></script>
    <script src="https://unpkg.com/htmx.org/dist/htmx.js"></script>
    {% django_htmx_script %}
    <script src="https://unpkg.com/hyperscript.org@0.9.12"></script>
    <script src="https://cdn.tailwindcss.com"></script>
    <style type="text/tailwindcss">
        [x-cloak] { 
            display: none !important; 
        }
        h1 {
            @apply text-4xl font-bold mb-4
        }
        h2 {
            @apply text-xl font-bold mb-2
        }
        p {
            @apply mb-4
        }
        .button, button, [type='submit'], [type='button'] {
            @apply bg-indigo-600 text-white font-bold px-6 py-4 inline-block 
            rounded-lg shadow-lg transition-all cursor-pointer
        }
        .button:hover, button:hover, [type='submit']:hover, [type='button']:hover {
            @apply bg-indigo-700
        }
        .button:active, button:active, [type='submit']:active, [type='button']:active {
            @apply scale-95
        }
        .button.alert, button.alert {
            @apply bg-red-700
        }
        .button.alert:hover, button.alert:hover {
            @apply bg-red-600
        }
        .button-red {
            @apply !bg-red-500 hover:!bg-red-600
        }
        .button-gray {
            @apply !bg-gray-300 hover:!bg-[#c3c9d0]
        }
        .navitems>li>a {
            @apply flex items-center gap-2 h-12 px-4 hover:bg-[rgba(31,41,55,0.3)] rounded-lg;
        }
        .hoverlist>* {
            @apply hover:bg-gray-100 rounded-md transition duration-150;
        }
        .hoverlist>*>a {
            @apply flex items-center p-2;
        }
        .highlight {
            @apply !bg-indigo-100;
        }
        .allauth content a {
            @apply underline underline-offset-2
        }
        .allauth content a:hover {
            @apply text-indigo-500
        }
        .allauth form[action="/accounts/signup/"] ul {
            @apply hidden
        }
        .allauth form[action="/accounts/signup/"] ul.errorlist {
            @apply block
        }
        .allauth .helptext {
            @apply block mt-4
        }
        {% comment %} label {
            @apply hidden
        } {% endcomment %}
        input[type=file] {
            @apply bg-white pl-0
        }
        .textarea, textarea, input {
            @apply w-full rounded-lg py-4 px-5 bg-gray-100
        }
        .errorlist li {
            @apply p-1 pl-4 border-l-red-500 border-l-4 border-solid mb-2 text-red-500
        }
        label[for="id_remember"] {
            @apply inline-block w-auto mr-2
        }
        input[name="remember"] {
            @apply w-auto
        }
        .alert-info { @apply bg-sky-600 }
        .alert-success { @apply bg-emerald-600 }
        .alert-warning { @apply bg-orange-600 }
        .alert-danger { @apply bg-red-600 }
    </style>
</head>
<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}' class="{% block class %}{% endblock %}">
	
    {% include 'includes/messages.html' %}

    {% include 'includes/header.html' %}

    {% block layout %}
    {% endblock %}

    {% block javascript %}{% endblock %}

</body>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Awesome</title>
    <link rel="shortcut icon" type="image/png" href="https://img.icons8.com/small/64/000000/fire-heart.png" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js" defer></script>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://unpkg.com/htmx.org/dist/htmx.js"></script>
    <style type="text/tailwindcss">
      [x-cloak] {
        display: none !important;
      }
      :root {
        --primary: rgb(88, 40, 244);
        --primary-hover: rgb(69, 29, 200);
        --black: #1f2937;
        --font1: 'Lobster', sans-serif;
      }
      h1 {
        @apply text-4xl font-bold mb-4;
      }
      h2 {
        @apply text-2xl font-bold mb-3;
      }
      h3 {
        @apply text-lg font-bold;
      }
      .font1 {
        font-family: var(--font1);
      }
      .button,
      button,
      [type='submit'],
      [type='button'] {
        display: inline-flex;
        flex-wrap: wrap;
        align-items: center;
        justify-content: center;
        flex-shrink: 0;
        text-align: center;
        border-radius: 0.5rem;
        cursor: pointer;
        padding: 0 1rem;
        min-height: 3.3rem;
        font-weight: 600;
        box-shadow: 0 4px 3px rgba(0, 0, 0, 0.1);
        transition-property: transform;
        transition-duration: 0.2s;
        color: white;
        background-color: var(--primary);
        width: fit-content;
      }
      .button:hover,
      button:hover,
      [type='submit']:hover,
      [type='button']:hover {
        background-color: var(--primary-hover);
      }
      .button:active,
      button:active,
      [type='submit']:active,
      [type='button']:active {
        transform: scale(0.95);
      }
      .secondaryAction {
        background-color: white;
        color: rgba(0, 0, 0, 0.6);
        border: 1px solid rgba(0, 0, 0, 0.3);
      }
      .secondaryAction:hover,
      .button.secondaryAction:hover {
        background-color: rgba(0, 0, 0, 0.05);
      }
      .navitems > li > a {
        @apply flex items-center gap-2 h-12 px-4 hover:bg-gray-700 rounded-lg;
      }
      .card {
        display: flex;
        flex-direction: column;
        overflow: hidden;
        position: relative;
        border-radius: 1rem;
        box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1);
        margin-bottom: 2rem;
        background-color: white;
        padding-bottom: 1rem;
        width: 100%;
      }
      .hoverlist > * {
        @apply hover:bg-gray-100 rounded-md transition duration-150;
      }
      .hoverlist > * > a {
        @apply flex items-center p-2;
      }
      .highlight {
        @apply !bg-indigo-100;
      }
      .titleBlip {
        animation: 1s fadeIn;
      }
      @keyframes fadeIn {
        0% {
          opacity: 0;
        }
        10% {
          opacity: 0;
        }
        100% {
          opacity: 1;
        }
      }
      html,
      body {
        margin: 0;
        min-height: 100%;
      }
      p {
        margin-bottom: 1rem;
      }
      form p {
        display: flex;
        align-items: center;
        margin-bottom: 1rem;
      }
      label,
      input {
        display: inline-block;
      }
      form p label {
        width: 7rem;
      }
      label {
        margin: 6px 0 3px;
      }
      input,
      textarea {
        width: 100%;
      }
      input[type='file'],
      select {
        background-color: white;
        padding-left: 0;
      }
      label[for='id_remember'] {
        width: auto;
        margin-right: 0.5rem;
      }
      input[name='remember'] {
        width: auto;
      }
      .btn-red {
        @apply inline-flex bg-red-500;
      }
      .btn-red:hover {
        @apply bg-red-600;
      }
      .login .secondaryAction {
        box-shadow: none;
        display: block;
        padding: none;
        padding: 0px;
        border: none;
        font-size: smaller;
        font-weight: normal;
        min-height: auto;
        margin-bottom: 1.5rem;
      }
      .login .secondaryAction:hover {
        @apply text-gray-500 underline bg-white;
      }
      #id_tags {
        margin-bottom: 1rem;
      }
      #id_tags div {
        display: inline-block;
        margin-right: 0.5rem;
      }
      #id_tags div label {
        border-radius: 9999px;
        padding: 0.5rem 1rem;
        border: 1px solid rgb(229 231 235);
        width: auto;
        cursor: pointer;
        user-select: none;
      }
      #id_tags input {
        display: none;
      }
      #id_tags label:has(input:checked) {
        background-color: var(--black);
        color: white;
        border: 1px solid var(--black);
      }
      .textarea,
      textarea {
        margin-bottom: 1rem;
      }
      .textarea,
      textarea,
      input {
        border-radius: 0.5rem;
        padding: 1rem 1.2rem;
        background-color: rgba(232, 240, 254, 1);
      }
      .errorlist li {
        color: rgb(253, 88, 49);
        padding: 0.5rem;
        padding-left: 1rem;
        border-left: 5px solid rgb(253, 88, 49);
        margin-bottom: 1rem;
      }
      .tab {
        cursor: pointer;
        padding: 0.75rem 1rem;
        color: rgb(0, 0, 0, 0.6);
        background-color: rgb(0, 0, 0, 0.05);
        border-radius: 0.75rem;
        text-align: center;
        display: flex;
        align-items: center;
      }
      .tab:hover {
        background-color: rgb(0, 0, 0, 0.1);
      }
      .tab.selected {
        color: white;
        background-color: var(--black);
      }
      .replyform {
        border-top: none;
      }
      .replyform textarea,
      .replyform input {
        padding: 0.75rem 1rem;
        font-size: 1rem;
        margin-bottom: 0px;
        height: 3.2rem;
      }
      .replyform button {
        margin-left: 0.5rem;
        min-height: unset;
      }
      .fade-me-in.htmx-settling {
        opacity: 0;
      }
      .fade-me-in {
        opacity: 1;
        transition: opacity 1s ease-out;
      }
      #profile article figure img {
        @apply aspect-[3/2] object-cover;
      }
      #profile article p {
        @apply truncate leading-normal;
      }
    </style>
  </head>
  <body class="bg-gray-100">
    {% include 'includes/header.html' %}

    <hero class="grid bg-gray-700 text-white text-center bg-cover z-10 relative bg-[url('https://live.staticflickr.com/65535/49909538937_3255dcf9e7_b.jpg')]">
      <div class="col-start-1 row-start-1 bg-gray-800 bg-opacity-40 w-full h-full"></div>
      <div class="col-start-1 row-start-1 py-24 px-10">
        <h1 class="font1 text-6xl title-fadein">Awesome Photos & Captions</h1>
        <p class="text-lg font-bold mb-5">Share your favorite Photos from Flickr and add a great caption</p>
        <a class="button" href="">Get Started</a>
      </div>
    </hero>
  </body>
</html>